test for addItem with bad input

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -32,82 +32,24 @@ if [[ $2 == 'merge' ]]; then
 fi
 
 # see if the user is trying to commit to the master branch
-if [ "$branch" = "master" ]; then
-	read -p "  You are about to commit to the master branch, are you sure? [y|n] " -n 1 -r < /dev/tty
-	echo
-	if echo $REPLY | grep -E '^[Yy]$' > /dev/null
-	then
-		exit 0 # commit will execute
-	fi
-	exit 1 # commit will not execute
-fi
+# if [ "$branch" = "master" ]; then
+# 	read -p "  You are about to commit to the master branch, are you sure? [y|n] " -n 1 -r < /dev/tty
+# 	echo
+# 	if echo $REPLY | grep -E '^[Yy]$' > /dev/null
+# 	then
+# 		exit 0 # commit will execute
+# 	fi
+# 	exit 1 # commit will not execute
+# fi
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
-ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
-
-if [[ "$STAGED_FILES" = "" ]]; then
-  exit 0
-fi
-
-PASS=true
-
-printf "\nValidating Javascript:\n"
-
-# Check for eslint
-if [[ ! -x "$ESLINT" ]]; then
-  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
-  exit 1
-fi
-
-for FILE in $STAGED_FILES
+for file in $(git diff --cached --name-only | grep -E '\.(js|jsx)$')
 do
-  "$ESLINT" "$FILE"
-
-  if [[ "$?" == 0 ]]; then
-    printf "\t\033[32mESLint Passed: $FILE\033[0m"
-  else
-    printf "\t\033[41mESLint Failed: $FILE\033[0m"
-    PASS=false
+  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
+  if [ $? -ne 0 ]; then
+    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
+    exit 1 # exit with failure status
   fi
 done
 
-printf "\nJavascript validation completed!\n"
-
-if ! $PASS; then
-  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
-  exit 1
-else
-  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-fi
-
-exit $?
-
-# is the current branch a direct child of the master branch?
-# echo "checking parent branch"
-# PARENT=$(git show-branch -a | grep -v `git rev-parse --abbrev-ref HEAD` | grep -v origin | sed 's/.*\[\(.*\)\].*/\1/' | grep -v -e '^$' | grep -v "^----$"
-# echo "parent branch is $PARENT")
-
-# see if the user is trying to commit to the master branch
-# echo "  you are trying to commit to the '$branch' branch"
-# if [ "$branch" = "master" ]; then
-#   echo "    you can't commit directly to the master branch"
-#   echo "    create a local feature branch first"
-#   echo
-#   exit 1
-# fi
-
-# check for valid branch name:
-
-# valid_branch_regex="^iss\d{3}\/[a-z\-]+$"
-
-# if [[ ! $local_branch =~ $valid_branch_regex ]]
-# then
-#     echo "invalid branch name"
-#     echo "  format is: 'iss000/issue-name'"
-#     echo "  replacing '000' with the issue number and 'issue-name' with the issue name"
-#     echo "  only lower-case letters and replace spaces in the issue name with dashes"
-#     echo "  rename your branch and try again"
-#     exit 1
-# fi
 
 echo "  commit successful..."
