changed form, no f and l name, updated all code to work

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,7 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e # using the options command to abort script at first error
-echo
 echo "PRE-COMMIT"
 
 EMAIL=$(git config user.email)
@@ -45,31 +44,43 @@ fi
 
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
 ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
+
 if [[ "$STAGED_FILES" = "" ]]; then
   exit 0
 fi
 
 PASS=true
 
+printf "\nValidating Javascript:\n"
+
+# Check for eslint
+if [[ ! -x "$ESLINT" ]]; then
+  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
+  exit 1
+fi
+
 for FILE in $STAGED_FILES
 do
-"$ESLINT" "$FILE"
+  "$ESLINT" "$FILE"
 
-if [[ "$?" == 0 ]]; then
-	printf "Passed $FILE"
-else
-	printf "Failed: $FILE"
-	PASS=false
-fi
+  if [[ "$?" == 0 ]]; then
+    printf "\t\033[32mESLint Passed: $FILE\033[0m"
+  else
+    printf "\t\033[41mESLint Failed: $FILE\033[0m"
+    PASS=false
+  fi
 done
 
-if ! = $PASS; then
-	printf "COMMIT FAILED: Your commit contains files that should pass ESLint but don't. Please fix."
-	exit 1
+printf "\nJavascript validation completed!\n"
+
+if ! $PASS; then
+  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  exit 1
 else
-	printf "COMMIT PASSED"
-	exit 0
+  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
+
+exit $?
 
 # is the current branch a direct child of the master branch?
 # echo "checking parent branch"
@@ -98,7 +109,5 @@ fi
 #     echo "  rename your branch and try again"
 #     exit 1
 # fi
-
-./node_modules/.bin/eslint .
 
 echo "  commit successful..."
